name: Full Code Review for Commit and Pull Request

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Python dependencies
        run: pip install openai

      - name: Full Code Review for Commit
        if: github.event_name == 'push'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: "gpt-4"
          PROMPT: "Review the following code changes with a focus on code quality."
          MAX_LENGTH: "8000"
          COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
        run: |
          for file in $(git diff --name-only HEAD^ HEAD); do
              echo "Reviewing file: $file"
              git show HEAD:$file | python3 scripts/commit_review.py --file $file
          done

      - name: Full Code Review for Pull Request
        if: github.event_name == 'pull_request'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: "gpt-4"
          PROMPT: "Suggest improvements for this code with a focus on maintainability and performance."
          MAX_LENGTH: "8000"
          PR_TITLE: "${{ github.event.pull_request.title }}"
          PR_BODY: "${{ github.event.pull_request.body }}"
        run: |
          for file in $(git diff --name-only origin/main HEAD); do
              echo "Reviewing file: $file"
              git show HEAD:$file | python3 scripts/pr_review.py --file $file
          done
